## 7가지 감정 데이터

In [33]:
import pandas as pd

df_exel = pd.read_excel("./dataset_raw/한국어_단발성_대화_데이터셋.xlsx")
emotions = ['행복', '분노', '혐오', '중립']
df_exel = df_exel[df_exel['Emotion'].isin(emotions)]
df_exel.columns = ['내용', 'label']
df_exel = df_exel[['label', '내용']]
df_exel

      label                                                 내용
11366    분노                        서해 수자원도 한류라서 그동안 불법조업 방치했나?
11367    분노                                           니가 인간이가.
11368    분노                          강아지를 때리고 유기하는것만 학대는 아닙니다!
11369    분노                              하여간 우리나라 교육엔 미래가 없어!!
11370    분노                           채널에이 군부 개인거 인증하냐 동아일보야!!
...     ...                                                ...
38589    혐오               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..
38590    혐오                                        재미가 없으니 망하지
38591    혐오  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...
38592    혐오               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ
38593    혐오               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요

[21961 rows x 2 columns]

In [38]:
label_map = {'행복':'긍정', '분노':'부정', '혐오':'부정'}
df_exel['label'] = df_exel['label'].map(label_map).fillna(df_exel['label'])
df_exel

      label                                                 내용
11366    부정                        서해 수자원도 한류라서 그동안 불법조업 방치했나?
11367    부정                                           니가 인간이가.
11368    부정                          강아지를 때리고 유기하는것만 학대는 아닙니다!
11369    부정                              하여간 우리나라 교육엔 미래가 없어!!
11370    부정                           채널에이 군부 개인거 인증하냐 동아일보야!!
...     ...                                                ...
38589    부정               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..
38590    부정                                        재미가 없으니 망하지
38591    부정  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...
38592    부정               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ
38593    부정               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요

[21961 rows x 2 columns]

In [ ]:
df_exel.to_csv()

## 네이버 평점 데이터

In [ ]:
df_txt = pd.read_csv("./dataset_raw/naver_shopping.txt", sep='\t', header=None, names = ['label', '내용'])
df_txt

        label                                                 내용
0           5                                            배공빠르고 굿
1           2                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
2           5  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
3           2  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
4           5                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ
...       ...                                                ...
199995      2                                    장마라그런가!!! 달지않아요
199996      5  다이슨 케이스 구매했어요 다이슨 슈퍼소닉 드라이기 케이스 구매했어요가격 괜찮고 배송...
199997      5                    로드샾에서 사는것보다 세배 저렴하네요 ㅜㅜ 자주이용할께요
199998      5                                      넘이쁘고 쎄련되보이네요~
199999      5   아직 사용해보지도않았고 다른 제품을 써본적이없어서 잘 모르겠지만 ㅎㅎ 배송은 빨랐습니다

[200000 rows x 2 columns]

In [23]:
label_map = {1:"부정", 2:"부정", 4:"긍정", 5:"긍정"}
df_txt['label'] = df_txt["label"].map(label_map).fillna(df_txt['label'])
df_txt

       label                                                 내용
0         긍정                                            배공빠르고 굿
1         부정                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
2         긍정  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
3         부정  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
4         긍정                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ
...      ...                                                ...
199995    부정                                    장마라그런가!!! 달지않아요
199996    긍정  다이슨 케이스 구매했어요 다이슨 슈퍼소닉 드라이기 케이스 구매했어요가격 괜찮고 배송...
199997    긍정                    로드샾에서 사는것보다 세배 저렴하네요 ㅜㅜ 자주이용할께요
199998    긍정                                      넘이쁘고 쎄련되보이네요~
199999    긍정   아직 사용해보지도않았고 다른 제품을 써본적이없어서 잘 모르겠지만 ㅎㅎ 배송은 빨랐습니다

[200000 rows x 2 columns]

## steam 리뷰 데이터

In [ ]:
df_txt2 = pd.read_csv("./dataset_raw/steam.txt", sep='\t', header=None, names = ['label', '내용'])
df_txt2

       label                                                 내용
0          0                                          노래가 너무 적음
1          0                    돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.
2          1                   막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지
3          1               차악!차악!!차악!!! 정말 이래서 왕국을 되찾을 수 있는거야??
4          1                시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요
...      ...                                                ...
99995      0                                       한글화해주면 10개산다
99996      0                                            개쌉노잼 ㅋㅋ
99997      0                             노잼이네요... 30분하고 지웠어요...
99998      1  야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기. 영어는 그리 어렵지 않습니다.
99999      1                     한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임

[100000 rows x 2 columns]

In [21]:
label_map = {0:"부정", 1:"긍정"}
df_txt2['label'] = df_txt2['label'].map(label_map).fillna(df_txt2['label'])
df_txt2

      label                                                 내용
0        부정                                          노래가 너무 적음
1        부정                    돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.
2        긍정                   막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지
3        긍정               차악!차악!!차악!!! 정말 이래서 왕국을 되찾을 수 있는거야??
4        긍정                시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요
...     ...                                                ...
99995    부정                                       한글화해주면 10개산다
99996    부정                                            개쌉노잼 ㅋㅋ
99997    부정                             노잼이네요... 30분하고 지웠어요...
99998    긍정  야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기. 영어는 그리 어렵지 않습니다.
99999    긍정                     한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임

[100000 rows x 2 columns]

## 내용 합치기

In [39]:
df_concat = pd.concat([df_txt,df_txt2, df_exel], axis=0)
df_concat

      label                                                 내용
0        긍정                                            배공빠르고 굿
1        부정                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
2        긍정  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
3        부정  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
4        긍정                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ
...     ...                                                ...
38589    부정               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..
38590    부정                                        재미가 없으니 망하지
38591    부정  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...
38592    부정               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ
38593    부정               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요

[321961 rows x 2 columns]

In [40]:
df_concat.to_csv('review_txt', sep='\t', index=False, encoding='utf-8')

In [45]:
print(df_concat[df_concat['label']=='긍정'])
print(df_concat[df_concat['label']=='부정'])

      label                                                 내용
0        긍정                                            배공빠르고 굿
2        긍정  아주좋아요 바지 정말 좋아서2개 더 구매했어요 이가격에 대박입니다. 바느질이 조금 ...
4        긍정                  민트색상 예뻐요. 옆 손잡이는 거는 용도로도 사용되네요 ㅎㅎ
10       긍정                              사이즈도 딱이고 귀엽고 넘 좋아요 ㅎㅎ
14       긍정                               촉감도 좋고 무게감이나 핏도 편합니다
...     ...                                                ...
33160    긍정                             유느님 내일 이면 해피투게더가하네요~^^
33161    긍정                            승관아~ 너에게 편지를 안 쓸 수가 없네.
33162    긍정                        패떴 개그계 큰 대모 이경실 씨 1탄 잘 봤습니다
33163    긍정                         유재석 오라버니 해피투게더 해피파출소 편 봤어요
33164    긍정                                 유재석 오라버니 해피투게더 봤어요

[155996 rows x 2 columns]
      label                                                 내용
1        부정                      택배가 엉망이네용 저희집 밑에층에 말도없이 놔두고가고
3        부정  선물용으로 빨리 받아서 전달했어야 하는 상품이었는데 머그컵만 와서 당황했습니다. 전...
5        부정  비추합니다 계란 뒤집을 때 완전 불편해요 ㅠㅠ 코팅도 묻어나고 보기엔 예쁘고 실용적...
6        부정  주문을 11월6에 시켰는데 11월16일에 배송이 왔네요 ㅎㅎㅎ 여기 회사측과는 전화...
7        부정                          넉넉한 길이로 주문했는데도 안 맞네요 별로예요
...     ...                                                ...
38589    부정               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..
38590    부정                                        재미가 없으니 망하지
38591    부정  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...
38592    부정               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ
38593    부정               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요

[161135 rows x 2 columns]